"use client";

import React from 'react';
import { mockAnalytics } from '@/data/mockAnalytics';
import { StatCard } from '@/components/ui/StatCard';
import { BarChart3, FileText, TrendingUp, Hash, Activity } from 'lucide-react';

export function AnalyticsPage() {
  const maxContentCount = Math.max(...mockAnalytics.contentByType.map(c => c.count));
  
  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div>
        <h1 className="text-2xl md:text-3xl font-bold text-white mb-2">Analytics</h1>
        <p className="text-gray-400">Track your podcast content performance and generation stats.</p>
      </div>

      {/* Metric Cards Row */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 md:gap-6">
        <StatCard
          title="Total Episodes"
          value={mockAnalytics.totalEpisodes}
          icon={BarChart3}
        />
        <StatCard
          title="Content Pieces"
          value={mockAnalytics.totalContentPieces}
          icon={FileText}
        />
        <StatCard
          title="Most Used Type"
          value={mockAnalytics.mostUsedContentType}
          icon={TrendingUp}
        />
        <StatCard
          title="Avg per Episode"
          value={mockAnalytics.avgContentPerEpisode}
          icon={Hash}
        />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Content by Type */}
        <div className="bg-gray-900 rounded-xl border border-gray-800 p-6 flex flex-col">
          <h2 className="text-lg font-bold text-white mb-6 flex items-center gap-2">
            <TrendingUp className="w-5 h-5 text-purple-400" />
            Content Generated by Type
          </h2>
          <div className="space-y-5 flex-1 justify-center flex flex-col">
            {mockAnalytics.contentByType.map((item, index) => {
              const width = `${(item.count / maxContentCount) * 100}%`;
              // Alternate gradient colors
              const gradients = [
                'from-purple-500 to-indigo-500',
                'from-indigo-500 to-cyan-500',
                'from-cyan-500 to-purple-500'
              ];
              const gradient = gradients[index % gradients.length];

              return (
                <div key={item.type} className="space-y-2">
                  <div className="flex justify-between text-sm">
                    <span className="text-gray-300 font-medium">{item.type}</span>
                    <span className="text-gray-400">{item.count} pieces</span>
                  </div>
                  <div className="h-2.5 bg-gray-800 rounded-full overflow-hidden">
                    <div 
                      className={`h-full bg-gradient-to-r ${gradient} rounded-full transition-all duration-1000 ease-out`}
                      style={{ width }}
                    />
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Weekly Activity */}
        <div className="bg-gray-900 rounded-xl border border-gray-800 p-6">
          <div className="flex items-center justify-between mb-8">
            <h2 className="text-lg font-bold text-white flex items-center gap-2">
              <BarChart3 className="w-5 h-5 text-indigo-400" />
              Weekly Activity
            </h2>
            <div className="flex items-center gap-4 text-xs font-medium">
              <div className="flex items-center gap-1.5 text-gray-300">
                <span className="w-2.5 h-2.5 rounded-full bg-purple-500"></span>
                Episodes
              </div>
              <div className="flex items-center gap-1.5 text-gray-300">
                <span className="w-2.5 h-2.5 rounded-full bg-cyan-500"></span>
                Content
              </div>
            </div>
          </div>
          
          <div className="h-[250px] flex items-end justify-between gap-2 pt-4">
            {mockAnalytics.weeklyActivity.map((week, index) => {
              const maxVal = Math.max(...mockAnalytics.weeklyActivity.map(w => Math.max(w.episodes, w.content)));
              const epHeight = `${(week.episodes / maxVal) * 100}%`;
              const contentHeight = `${(week.content / maxVal) * 100}%`;
              
              return (
                <div key={index} className="flex-1 flex flex-col items-center gap-3 group relative h-full">
                  <div className="flex-1 w-full flex items-end justify-center gap-1.5 relative">
                    <div 
                      className="w-1/3 max-w-[12px] bg-purple-500/80 hover:bg-purple-400 rounded-t-sm transition-colors"
                      style={{ height: epHeight, minHeight: '4px' }}
                      title={`${week.episodes} Episodes`}
                    />
                    <div 
                      className="w-1/3 max-w-[12px] bg-cyan-500/80 hover:bg-cyan-400 rounded-t-sm transition-colors"
                      style={{ height: contentHeight, minHeight: '4px' }}
                      title={`${week.content} Content Pieces`}
                    />
                  </div>
                  <span className="text-xs text-gray-500 font-medium">{week.week}</span>
                </div>
              );
            })}
          </div>
        </div>
      </div>

      {/* Recent Activity Feed */}
      <div className="bg-gray-900 rounded-xl border border-gray-800 p-6">
        <h2 className="text-lg font-bold text-white mb-6 flex items-center gap-2">
          <Activity className="w-5 h-5 text-cyan-400" />
          Recent Activity
        </h2>
        
        <div className="space-y-6">
          {mockAnalytics.recentActivity.map((activity, index) => (
            <div key={index} className="flex items-start gap-4">
              <div className="w-8 h-8 rounded-full bg-gray-800 border border-gray-700 flex items-center justify-center flex-shrink-0 mt-0.5">
                <span className="w-2 h-2 rounded-full bg-gradient-to-r from-purple-500 to-cyan-500" />
              </div>
              <div className="flex-1 min-w-0 flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                <div>
                  <p className="text-gray-300 text-sm">
                    {activity.action} <span className="text-white font-medium">"{activity.podcast}"</span>
                  </p>
                  <p className="text-gray-500 text-xs mt-1">
                    {new Date(activity.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' })}
                  </p>
                </div>
                <div className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-medium bg-gray-800 text-gray-300 border border-gray-700">
                  {activity.type}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
